# General sensor definitions.
dataset: airsim_car
ncam: 2

camera_0:
  topic: /airsim_node/Car1/camera_left/Scene
  # Sensor extrinsics wrt. the body-frame.
  T_BS:
    cols: 4
    rows: 4
    data: [0.0, 0.0, 1.0, 2.0,
           -1.0, 0.0, 0.0, 0.1,
           0.0, -1.0, 0.0, 1.10,
           0.0, 0.0, 0.0, 1.0]
  
  # Camera specific definitions.
  rate_hz: 5
  resolution: [640, 480]
  projection_model: pinhole
  intrinsics: [320, 320, 320.0, 240.0] # fu, fv, cu, cv
  distortion_model: None
  distortion_coefficients: [0, 0, 0, 0]

camera_1:
  topic: /airsim_node/Car1/camera_right/Scene
  # Sensor extrinsics wrt. the body-frame.
  T_BS:
    cols: 4
    rows: 4
    data: [0.0, 0.0, 1.0, 2.0,
           -1.0, 0.0, 0.0, -0.1,
           0.0, -1.0, 0.0, 1.10,
           0.0, 0.0, 0.0, 1.0]
  # Camera specific definitions.
  rate_hz: 5
  resolution: [640, 480]
  projection_model: pinhole
  intrinsics: [320, 320, 320.0, 240.0] # fu, fv, cu, cv
  distortion_model: None
  distortion_coefficients: [0, 0, 0, 0]

imu:
  topic: /airsim_node/Car1/imu/IMU
  # Sensor extrinsics wrt. the body-frame.
  T_BS:
    cols: 4
    rows: 4
    data: [1.0, 0.0, 0.0, 0.0,
           0.0, 1.0, 0.0, 0.0,
           0.0, 0.0, 1.0, 0.0,
           0.0, 0.0, 0.0, 1.0]
  
  rate_hz: 100

  # Inertial sensor noise model parameters (static)
  gyroscope_noise_density: 0.001 #0.01 #0.000084    # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 0.00001 #0.00001 #0.000001       # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  accelerometer_noise_density: 0.2 #0.1 #0.002273  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 0.0001 #0.0001 #0.000014    # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
